source "https://rubygems.org"

gem "jekyll", "3.9.3"
gem "html-proofer", "3.19.4"
gem "jekyll-remote-theme"
gem "deep_merge"
gem "jekyll-open-sdg-plugins", "2.3.0"
gem "jekyll-redirect-from"
gem "jekyll-toc"
gem "kramdown-parser-gfm"
gem "webrick"
