name: Accessibility

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v1.4.2

    - name: Build and serve site
      run: | 
        docker build -t buildsite ./scripts/accessibility_testing/.
        docker run --rm -v $PWD:/site buildsite
        docker run -d --rm -p 80:80 -v $PWD/_site:/usr/local/apache2/htdocs/sdg-indicators --name jekyllbuildserver httpd:2.4.41-alpine

    - name: Run accessibility tests
      run: |
        npx pa11y-ci --config ./scripts/accessibility_testing/configurations/desktop.json
        npx pa11y-ci --config ./scripts/accessibility_testing/configurations/mobile.json
        npx pa11y-ci --config ./scripts/accessibility_testing/configurations/contrast.json