name: Accessibility

on: [pull_request]

jobs:
  accessibility-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v1.4.2

    - name: Build and serve website
      run: |
        docker build -t buildsite ./scripts/accessibility-test/.
        docker run --rm -v $PWD:/site buildsite
        docker run -d --rm -p 80:80 -v $PWD/_site:/usr/local/apache2/htdocs/sdg-indicators --name jekyllbuildserver httpd:2.4.41-alpine
    
    - name: Run accessibility tests
      run: cd ./scripts/accessibility-test && yarn && yarn test
